// ...existing code...
// Remove unused imports
// import { LineChart, Line, RadarChart, PolarGrid } from 'recharts';
// ...existing code...
useEffect(() => {
  // ...existing code...
}, [yearFilter]); // Add yearFilter to dependencies
// ...existing code...
